"""Generate a bounded item/model allowlist from pinned SQL and installed vanilla assets."""
from pathlib import Path
import ctypes as C,gzip,re,struct,json
import read_client_data as client
from build_catalog import catalog_row, read_item_templates, read_quest_minimums, render_row
root=Path(__file__).resolve().parents[1]
sql=gzip.open(root/'research/classic.sql.gz','rt').read()
items=[]
for d in read_item_templates(sql):
 inv=d['InventoryType'];cl=d['class']
 if (cl==2 and inv in (13,15,17,21,22,25,26)) or (cl==4 and inv==14) or cl==11:items.append(d)
quest_levels=read_quest_minimums(sql,items)
for archive in ['patch-2.MPQ','patch.MPQ','dbc.MPQ','model.MPQ','texture.MPQ','interface.MPQ']:
 h=C.c_void_p()
 if client.lib.SFileOpenArchive(str(client.game/archive).encode(),0,0x100,C.byref(h)):client.archives.append(h)
b=client.read('DBFilesClient\\ItemDisplayInfo.dbc');magic,n,fields,size,ss=struct.unpack_from('<4s4I',b);assert magic==b'WDBC' and fields==23
strings=b[20+n*size:];displays={}
def string(i):return strings[i:].split(b'\0')[0].decode('ascii')
for i in range(n):
 row=struct.unpack_from('<23I',b,20+i*size);displays[row[0]]=row
available=set()
for h in client.archives:
 previous=client.archives;client.archives=[h]
 available.update(x.lower() for x in (client.read('(listfile)') or b'').decode(errors='replace').splitlines())
 client.archives=previous
assets=[];quivers=[]
for d in sorted(items,key=lambda d:d['entry']):
 row=displays.get(d['displayid'])
 if not row:continue
 model,skin=string(row[1]),string(row[3])
 if not model or not skin:continue
 kind=5 if d['class']==11 else 3 if d['InventoryType']==14 else 4 if d['InventoryType'] in (15,25,26) else 2 if d['InventoryType']==17 else 1
 folder='Quiver' if kind==5 else 'Shield' if kind==3 else 'Weapon'
 base='Item\\ObjectComponents\\'+folder+'\\'
 modelPath=base+model;texturePath=base+skin+'.blp'
 if re.sub(r'\.mdx$','.m2',modelPath,flags=re.I).lower() not in available or texturePath.lower() not in available:continue
 assets.append((d['entry'],d['displayid'],kind,d['subclass'],d['InventoryType'],d['sheath'],modelPath,texturePath))
 if kind==5:quivers.append(catalog_row(d,string(row[5]),quest_levels))
header='// Generated by tools/build_weapon_assets.py; paths only, no Blizzard assets.\n#pragma once\nstruct WeaponAsset { unsigned item,display,kind,subclass,inventory,sheath; const char* model; const char* texture; };\nstatic const WeaponAsset weaponAssets[]={\n'
for row in assets:header+='{'+','.join(json.dumps(v) for v in row)+'},\n'
header+='};\ninline const WeaponAsset* weaponAsset(unsigned id){\n unsigned lo=0,hi=sizeof(weaponAssets)/sizeof(weaponAssets[0]);\n while(lo<hi){unsigned mid=lo+(hi-lo)/2;if(weaponAssets[mid].item<id)lo=mid+1;else hi=mid;}\n return lo<sizeof(weaponAssets)/sizeof(weaponAssets[0])&&weaponAssets[lo].item==id?&weaponAssets[lo]:nullptr;\n}\n'
(root/'native/WeaponAssets.h').write_text(header)
lua='-- Generated vanilla weapon allowlist and quivers; see CATALOG-SOURCE.json.\nSaureksClosetWeaponAssets={\n'
for row in assets:lua+='[%d]={%d,%d},\n'%(row[0],row[2],row[3])
lua+='}\nSaureksClosetQuivers={\n'
for row in quivers:lua+='{'+render_row(row)+'},\n'
lua+='}\n';(root/'addon/SaureksCloset/WeaponData.lua').write_text(lua)
for h in client.archives:client.lib.SFileCloseArchive(h)
print('Verified assets:',len(assets),'Quiver items:',len(quivers),'families:',{k:sum(a[2]==k for a in assets) for k in range(1,6)})
assert assets and quivers
