"""Build the vanilla visible-equipment catalog from the pinned CMaNGOS SQL dump."""
import gzip
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
source = ROOT / 'research/classic.sql.gz'
sql = gzip.open(source, 'rt').read()
schema = sql.split('CREATE TABLE `item_template` (', 1)[1].split(') ENGINE=', 1)[0]
columns = re.findall(r'^  `([^`]+)`', schema, re.M)
# SQL dump rows: strings may contain commas, parentheses, escaped apostrophes.
token = re.compile(r"'((?:\\.|[^'\\])*)'|([^,()]+)|([,()])")
escapes = {'n': '\n', 'r': '\r', 't': '\t', '0': '\0', 'Z': '\x1a'}
visible = {1, 3, 4, 5, 6, 7, 8, 9, 10, 13, 14, 15, 16, 17, 19, 20, 21, 22, 23, 25, 26}
items = {}
for statement in re.findall(r'^INSERT INTO `item_template` VALUES (.*);$', sql, re.M):
    row = None
    for m in token.finditer(statement):
        s, number, punctuation = m.groups()
        if punctuation == '(':
            row = []
        elif punctuation == ')':
            assert len(row) == len(columns), (len(row), len(columns))
            d = dict(zip(columns, row))
            if d['InventoryType'] in visible and d['displayid'] > 0 and d['class'] in (2, 4):
                items[d['entry']] = [d[k] for k in ('entry', 'name', 'InventoryType', 'Quality', 'class', 'subclass', 'ItemLevel', 'displayid', 'itemset')]
        elif s is not None:
            row.append(re.sub(r'\\(.)', lambda e: escapes.get(e[1], e[1]), s))
        elif number is not None and row is not None:
            row.append(float(number) if '.' in number else int(number))
out = ROOT / 'addon/SaureksCloset/Catalog.lua'
with out.open('w') as f:
    f.write('-- Generated by tools/build_catalog.py; see CATALOG-LICENSE.md.\n')
    f.write('-- id, name, inventory type, quality, class, subclass, item level, display ID, set ID\nVanityStudioCatalog = {\n')
    for item in sorted(items.values(), key=lambda i: (i[1].lower(), i[0])):
        f.write('{' + ','.join(json.dumps(v, ensure_ascii=False) for v in item) + '},\n')
    f.write('}\n')
meta = {'source': 'https://github.com/cmangos/classic-db', 'revision': json.load(open(ROOT / 'research/db-tree.json'))['sha'], 'dump': 'Full_DB/ClassicDB_1_12_1_z2815.sql.gz', 'sha256': hashlib.sha256(source.read_bytes()).hexdigest(), 'count': len(items), 'scope': 'Visible vanilla armor, shirts, tabards, shields and weapons; includes unused/developer entries present in the database. Server custom items are not included.'}
(ROOT / 'addon/SaureksCloset/CATALOG-SOURCE.json').write_text(json.dumps(meta, indent=2) + '\n')
print(json.dumps(meta, indent=2))
