import struct,json
from pathlib import Path
r=Path(__file__).resolve().parents[1]
def rows(name):
 b=(r/'research/client-data'/name).read_bytes();magic,n,f,size,ss=struct.unpack_from('<4s4I',b);assert magic==b'WDBC'
 return [struct.unpack_from('<'+'I'*f,b,20+i*size) for i in range(n)]
sections=rows('CharSections.dbc');hairs=rows('CharHairGeosets.dbc');facials=rows('CharacterFacialHairStyles.dbc')
races={1:('Human',49,50),2:('Orc',51,52),3:('Dwarf',53,54),4:('Night Elf',55,56),5:('Undead',57,58),6:('Tauren',59,60),7:('Gnome',1563,1564),8:('Troll',1478,1479)}
def lua(v):
 if isinstance(v,dict):return '{'+','.join('['+lua(k)+']='+lua(val) for k,val in sorted(v.items(),key=lambda x:str(x[0])))+'}'
 if isinstance(v,(list,tuple)):return '{'+','.join(map(lua,v))+'}'
 return json.dumps(v)
data={}; valid=[]
for race in races:
 data[race]={}
 for sex in (0,1):
  sec=[x for x in sections if x[1]==race and x[2]==sex and x[9]==0]
  skin=sorted({x[5] for x in sec if x[3]==0})
  faces={s:sorted({x[4] for x in sec if x[3]==1 and x[5]==s}) for s in skin}
  hair=sorted({x[3] for x in hairs if x[1]==race and x[2]==sex})
  colors={h:sorted({x[5] for x in sec if x[3]==3 and x[4]==h}) for h in hair}
  # Bald styles may have no texture row; the color is still a legal byte.
  allcolors=sorted({x[5] for x in sec if x[3]==3}) or [0]
  for h in colors:
   if not colors[h]:colors[h]=allcolors
  facial=sorted({x[2] for x in facials if x[0]==race and x[1]==sex}) or [0]
  for s in skin: assert faces[s],(race,sex,s)
  d={'skin':skin,'faces':faces,'hairStyle':hair,'hairColors':colors,'facial':facial}
  data[race][sex]=d
  for s in skin:
   for f in faces[s]:valid.append((race,sex,0,s,f))
  for h in hair:
   for c in colors[h]:valid.append((race,sex,1,h,c))
  for f in facial:valid.append((race,sex,2,f,0))
  print(race,sex,'skin',len(skin),'faces',len(faces[skin[0]]),'hair',len(hair),'facial',len(facial))
(r/'addon/SaureksCloset/BodyData.lua').write_text('-- Generated from this client\'s vanilla character DBCs. Indices are zero-based.\nVanityStudioBodyOptions='+lua(data)+'\nVanityStudioRaces='+lua(races)+'\n')
(r/'native/BodyOptions.h').write_text('// Generated by tools/build_body_data.py\n#pragma once\nstruct BodyOption { unsigned char race,sex,kind,a,b; };\nstatic const BodyOption bodyOptions[] = {\n'+''.join('{'+','.join(map(str,v))+'},\n' for v in valid)+'};\n')
(r/'research/body-options.json').write_text(json.dumps(data,indent=2))
